receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlphttp:
    endpoint: https://otlp.nr-data.net:4318
    headers:
      api-key: NEW_RELIC_API_KEY
connectors:
  forward:
  spanmetrics:
    histogram:
      explicit:
    dimensions: 
      - name: http.method
        default: "GET"
      - name: http.status_code
processors:
  probabilistic_sampler:
    sampling_percentage: 20

      
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [spanmetrics, forward]
    traces/sampling:
      receivers: [forward]
      processors: [probabilistic_sampler]
      exporters: [otlphttp]
    metrics:
      receivers: [spanmetrics]
      exporters: [otlphttp]
